# Quix Project Descriptor
# This file describes the data pipeline and configuration of resources of a Quix Project.

metadata:
  version: 1.0

# This section describes the Deployments of the data pipeline
deployments: []

# This section describes the Topics of the data pipeline
topics:
- name: sfdsfsf
  persisted: false
  configuration:
    partitions: 2
    replicationFactor: 2
    retentionInMinutes: 60
    retentionInBytes: 52428800
- name: deste
  persisted: false
  configuration:
    partitions: 2
    replicationFactor: 2
    retentionInMinutes: 60
    retentionInBytes: 52428800
- name: test
  persisted: false
  configuration:
    partitions: 2
    replicationFactor: 2
    retentionInMinutes: 60
    retentionInBytes: 52428800

# This section describes the Applications of the data pipeline
applications: []
